name: Build Static Site

on:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/initialize
      - uses: pnpm/action-setup@v2.2.0
        with:
          version: 7.1.7
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - name: Build Static Site
        run: |
          pnpm run build
