name: Release Workflow

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          submodules: recursive
      - uses: ./.github/actions/initialize
      - uses: pnpm/action-setup@v2.2.0
        with:
          version: 7.1.7
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - name: Build
        run: |
          SENTRY_ENVIRONMENT=production DEPLOY_SENTRY=true SENTRY_RELEASE=${{ github.event.release.tag_name }} pnpm run build
        env:
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ENVIRONMENT: ${{ secrets.SENTRY_ENVIRONMENT }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_DSN_URL: ${{ secrets.SENTRY_DSN_URL }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
